#!/bin/bash
yum update -y
yum install git -y
amazon-linux-extras install nginx1
systemctl start nginx
# run the rest manually, don't want these running as root anyway
# curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
# . ~/.nvm/nvm.sh
# nvm install node
